const fs = require('fs');
const path = require('path');

// __dirname is scripts
// so to get to material-symbols-json where the JSONs are:
const iconsJsonPath = path.resolve(__dirname, '../icons-outlined.json');


const outputPath = path.resolve(__dirname, '../src/IconSet.ts');


if (!fs.existsSync(iconsJsonPath)) {
  console.error(`Error: Could not find icons.json at ${iconsJsonPath}`);
  console.log('Please run download_fonts.sh in the root directory first.');
  process.exit(1);
}

const icons = JSON.parse(fs.readFileSync(iconsJsonPath, 'utf8'));
const iconNames = Object.keys(icons);

const tsContent = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by scripts/generate-types.js based on ../icons.json

export type IconName = 
  | ${iconNames.map(name => `'${name}'`).join('\n  | ')};

export const iconNames: IconName[] = [
  ${iconNames.map(name => `'${name}'`).join(',\n  ')}
];

export const iconMap: Record<IconName, number> = ${JSON.stringify(icons, null, 2)};
`;

fs.writeFileSync(outputPath, tsContent, 'utf8');

console.log(`✅ Successfully generated IconSet.ts with ${iconNames.length} icons.`);
